Typescript assingnment
razarehan28/TypescriptPractical pull request #1
Opened 2022-04-28 07:43 UTC by razarehan28

2022-04-28 12:46 UTC, Rutvi25 requested changes

2022-04-28 12:46 UTC, Rutvi25 commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
remove unnecessary code

2022-04-28 12:46 UTC, Rutvi25 commented on src/calc.ts
> +let calScreen = <HTMLElement>document.querySelector(".calculator-screen");
types can be given to the variables, i.e. HTMLInputElement or HTMLButtonElement etc.

2022-04-28 12:46 UTC, Rutvi25 commented on src/calc.ts
> +// function mod(num) {
remove unnecessary code

2022-04-29 09:48 UTC, harshpatel-javascript approved these changes

2022-05-03 09:26 UTC, desaianiruddh commented on calc.html
> +              <div id="memory-clear" class="btn">MC</div>
id should be in camelCase convention

2022-05-03 09:33 UTC, desaianiruddh commented on src/calc.ts
> +  let ch = e.target as HTMLElement;
needs to use meaningful name of variables

2022-05-03 09:37 UTC, desaianiruddh commented on src/calc.ts
> +function memoryMinus() {
add return type for function

2022-05-03 09:38 UTC, desaianiruddh commented on src/calc.ts
> +function memoryStored() {
add return type for function

2022-05-03 09:38 UTC, desaianiruddh commented on src/calc.ts
> +function memoryClear() {
add return type

2022-05-06 06:19 UTC, sheth-jay approved these changes

2022-05-06 09:30 UTC, merged